


spring:
  config:
    activate:
      on-profile:
        - dev
  cloud:
    gateway:
      routes:

        - id: curriculum-service
          uri: ${CURRICULUM_SERVICE_URI_DEV:http://localhost:8085}
          predicates:
            - Path=/curriculum-service/**
          filters:
            - StripPrefix=1

        - id: user-service
          uri: ${USER_SERVICE_URI_DEV:http://localhost:8083}
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

