spring:
  application:
    name: api-gateway
---
server:
  port: ${API_GATEWAY_PORT:9222}


spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}


springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    urls:
      - name: curriculum-service
        url: /curriculum-service/v3/api-docs

      - name: user-service
        url: /user-service/v3/api-docs
    with-credentials: true

auth:
  public-urls: ${PUBLIC_URL:/api/v2/users/login,/api/v1/users/refresh-token,/api/v1/users/forgot-password,/api/v1/users/verify-otp, /api/v1/users/sign-up}
