apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: nhduy0909/lms-api-gateway:1.0
          ports:
            - containerPort: 9091
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9091
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9091
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
          envFrom:
            - configMapRef:
                name: lms-config-map # not found config
---
# Config service
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    app: api-gateway-service
spec:
  type: ClusterIP
  selector:
    app: api-gateway
  ports:
    - name: api-gateway
      port: 9091
      targetPort: 9091
