services:

  eureka-server-lms:
    container_name: eureka-server-lms
    image: nhduy0909/production-lms-eureka-server:1.0.2
    ports:
      - "8761:8761"
    env_file:
      - .env
    networks:
      - application_lms_network
    restart: always

  user-service-lms:
    container_name: user-service-lms
    image: nhduy0909/production-lms-user-service:1.0.3
    ports:
      - "8083:8083"
      - "9221:9221"
    env_file:
      - .env
    depends_on:
      eureka-server-lms:
        condition: service_started
    networks:
      - application_lms_network
    restart: always

  curriculum-service-lms:
    container_name: curriculum-service-lms
    image: nhduy0909/production-lms-curriculum-service:1.0.2
    ports:
      - "8085:8085"
    env_file:
      - .env
    depends_on:
      eureka-server-lms:
        condition: service_started
    networks:
      - application_lms_network
    restart: always

  api-gateway-lms:
    container_name: api-gateway-lms
    image: nhduy0909/production-lms-api-gateway:1.0.2
    ports:
      - "9222:9222"
    env_file:
      - .env
    depends_on:
      eureka-server-lms:
        condition: service_started
    networks:
      - application_lms_network
    restart: always

networks:
  application_lms_network:
    external: true