spring:
  config:
    activate:
      on-profile: prod
    import: optional:file:.env[.properties],optional:file:../.env[.properties]
  datasource:
    url: jdbc:postgresql://${USER_SERVICE_DB_HOST}:${USER_SERVICE_DB_PORT}/${USER_SERVICE_DB_NAME}
    username: ${USER_SERVICE_DB_USERNAME}
    password: ${USER_SERVICE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:false}
  cache:
    type: redis
    redis:
      time-to-live: ${REDIS_TTL:600000ms}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  rabbitmq:
    port: ${RABBITMQ_PORT:5672}
    host: ${RABBITMQ_HOST}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: hotrotoyworld@gmail.com
    password: tknm zdhx fiox vazw
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLE:true}
  threads:
    virtual:
      enabled: true


jwt:
  secretKey: ${JWT_SECRET_KEY:}
  accessTokenExpirationTime: ${JWT_ACCESS_TOKEN_EXPIRATION:259200000} # 3 days
  refreshTokenExpirationTime: ${JWT_REFRESH_TOKEN_EXPIRATION:2419200000} # 2 weeks
  resetPasswordTokenExpirationTime: ${JWT_RESET_PASSWORD_TOKEN_EXPIRATION:900000} # 15 minutes

rabbitmq:
  exchange-name: ${USER_SERVICE_RABBITMQ_EXCHANGE_NAME}
  user-mail-routing-key: ${USER_SERVICE_RABBITMQ_USER_MAIL_ROUTING_KEY}
  user-mail-queue: ${USER_SERVICE_RABBITMQ_USER_MAIL_QUEUE}

  cache-data-queue: ${RABBITMQ_CACHE_DATA_QUEUE}

server:
  port: ${USER_SERVICE_PORT}

cloudinary:
  cloudinary-name: ${USER_SERVICE_CLOUDINARY_NAME}
  api-key: ${USER_SERVICE_CLOUDINARY_API_KEY}
  api-secret: ${USER_SERVICE_CLOUDINARY_API_SECRET}

grpc:
  server:
    security:
      enabled: ${GRPC_SERVER_SECURITY_ENABLED:false}
    port: ${USER_SERVICE_GRPC_SERVER_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

curriculum-service: curriculum-service-lms