spring:
  application:
    name: ${USER_SERVICE_SPRING_APPLICATION_NAME:user-service}
  config:
    import: optional:file:.env[.properties],optional:file:../.env[.properties]
  datasource:
    url: ${USER_SERVICE_DB_URL:jdbc:postgresql://localhost:5432/db_user_service_lms}
    username: ${USER_SERVICE_DB_USERNAME:postgres}
    password: ${USER_SERVICE_DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: ${USER_SERVICE_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${USER_SERVICE_JPA_FORMAT_SQL:false}
  data:
    redis:
      host: ${GLOBAL_REDIS_HOST:localhost}
      port: ${GLOBAL_REDIS_PORT:6379}
  rabbitmq:
    port: ${USER_SERVICE_RABBITMQ_PORT:5672}
    host: ${USER_SERVICE_RABBITMQ_HOST:localhost}
    username: ${USER_SERVICE_RABBITMQ_USERNAME:guest}
    password: ${USER_SERVICE_RABBITMQ_PASSWORD:guest}
  mail:
    host: ${USER_SERVICE_MAIL_HOST:smtp.gmail.com}
    port: ${USER_SERVICE_MAIL_PORT:587}
    username: ${USER_SERVICE_MAIL_USERNAME:}
    password: ${USER_SERVICE_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${USER_SERVICE_MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${USER_SERVICE_MAIL_SMTP_STARTTLS_ENABLE:true}

jwt:
  secretKey: ${USER_SERVICE_JWT_SECRET_KEY:}
  accessTokenExpirationTime: ${USER_SERVICE_JWT_ACCESS_TOKEN_EXPIRATION:259200000} # 3 days
  refreshTokenExpirationTime: ${USER_SERVICE_JWT_REFRESH_TOKEN_EXPIRATION:2419200000} # 2 weeks
  resetPasswordTokenExpirationTime: ${USER_SERVICE_JWT_RESET_PASSWORD_TOKEN_EXPIRATION:900000} # 15 minutes

rabbitmq:
  exchange-name: ${USER_SERVICE_RABBITMQ_EXCHANGE_NAME:demo}
  user-mail-routing-key: ${USER_SERVICE_RABBITMQ_USER_MAIL_ROUTING_KEY:demo}
  user-mail-queue: ${USER_SERVICE_RABBITMQ_USER_MAIL_QUEUE:lms-queue}

  exchange-cache-data-name: ${USER_SERVICE_RABBITMQ_EXCHANGE_CACHE_DATA_NAME:cache-lecturers-data}
  cache-data-routing-key: ${USER_SERVICE_RABBITMQ_CACHE_DATA_ROUTING_KEY:cache-lecturers-data}
  cache-data-queue: ${USER_SERVICE_RABBITMQ_CACHE_DATA_QUEUE:cache-data-queue}

server:
  port: ${USER_SERVICE_SERVER_PORT:8083}

cloudinary:
  cloudinary-name: ${USER_SERVICE_CLOUDINARY_NAME:dvynemzxx}
  api-key: ${USER_SERVICE_CLOUDINARY_API_KEY:368324453129176}
  api-secret: ${USER_SERVICE_CLOUDINARY_API_SECRET:FyxpYajXxv58KvfsbG9mYuYWOh8}

grpc:
  server:
    security:
      enabled: ${USER_SERVICE_GRPC_SERVER_SECURITY_ENABLED:false}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %clr([%thread]){faint} %clr(%-5level) %clr(%logger{1}){cyan} %clr(%X{requestId}){yellow} - %clr(%X{email}){green} - %msg%n"

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_DOMAIN:localhost}:${EUREKA_PORT:8761}/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
