spring:
  application:
    name: LMS
  datasource:
    url: jdbc:postgresql://localhost:5432/db_curriculum_service_lms
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis
    redis:
      time-to-live: 600000ms
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
server:
  port: 8085
---
grpc:
  client:
    parse-token:
      address: 'static://localhost:9090'
      negotiationType: plaintext
    instructor:
      address: 'static://localhost:9090'
      negotiationType: plaintext
---
rabbitmq:
  exchange-name: ache-lecturers-data
  cache-data-routing-key: cache-lecturers-data
  cache-data-queue: cache-data-queue
  exchange-create-tests-name: create-tests-exchange
  create-tests-routing-key: create-tests-routing-key
  create-tests-queue: create-tests-queue
---
minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: 12345678
  thumbnail-bucket: thumbnail-bucket
  video-bucket: video-bucket

